model:
  name: colight
  train_model: true
  epsilon: 0.8
  epsilon_decay: 0.99995
  epsilon_min: 0.05
  batch_size: 8
trainer:
  episodes: 1
  steps: 3600
  test_steps: 3600
  learning_start: 1000000000
  buffer_size: 5000
  action_interval: 10
  update_model_rate: 1
  update_target_rate: 10
  test_when_train: false
  evaluation_episodes:
  - 0
  - 1
  resumable_checkpoint_episodes:
  - 0
  - 1
  event_schedule_plan: configs/events/plans/att004_state_lib_v1.yml
logger:
  save_rate: 25
  attention: false
