includes:
  - configs/tsc/sga_colight_text_event_smoke.yml

model:
  name: concat_colight
  sga_enabled: True
  sga_input_mode: concat
  batch_size: 8

trainer:
  episodes: 2
  steps: 300
  test_steps: 300
  learning_start: 20
  buffer_size: 500
  event_schedule: configs/events/hz4x4.yml

logger:
  save_rate: 1
  attention: true
