includes:
  - configs/tsc/base.yml

model:
  name: dqn
  train_model: True
  epsilon: 0.1
  epsilon_decay: 0.995
  epsilon_min: 0.01
  one_hot: True
  phase: True

trainer:
  episodes: 400
  learning_start: 1000
  buffer_size: 5000
  evaluation_episodes: [0, 10, 25, 50, 100, 150, 200, 250, 300, 350, 400]
