"""Generate a frozen per-episode random event plan (sumo-episode-plan-v1).

Deterministic given --seed: the same YAML is regenerated byte-identically for
the same arguments, and every method/seed shares one plan file so training
remains paired.  Targets are validated against the real network catalog at
generation time (external motor-vehicle lanes for lane_blockage, external
directed edges for road_closure), so plan-time failures surface here, not
inside a training run.
"""
import argparse
import hashlib
import json
from pathlib import Path
import random
import sys

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from world.sumo_events.plans import PLAN_SCHEMA, load_plan  # noqa: E402
from world.sumo_events.runtime import SumoEventRuntime  # noqa: E402
from world.sumo_events.schema import Schedule  # noqa: E402

DEFAULT_NET = ('data/raw_data/hangzhou_4x4_gudang_18041610_1h/'
               'hangzhou_4x4_gudang_18041610_1h.net.xml')
DEFAULT_EVAL = 'configs/events/hz4x4_comparison.yml'

KINDS = ('lane_blockage', 'road_closure', 'global_rain')


def catalog(net_file):
    runtime = SumoEventRuntime(net_file, Schedule(()))
    lanes = {k: v for k, v in runtime.network_catalog().items()
             if v['motor_vehicle_lane'] and not v['internal']}
    edges = {e for v in lanes.values() for e in [v['edge_id']]}
    return runtime, lanes, edges


def sample_event(rng, kind, index, episode, args, lanes, edges):
    event_id = f'ep{episode:04d}_e{index}'
    begin = rng.randint(args.begin_min, args.begin_max)
    duration = rng.randint(args.dur_min, args.dur_max)
    end = min(begin + duration, args.horizon - args.recovery)
    if kind == 'global_rain':
        return {'event_id': event_id, 'kind': kind, 'begin': begin, 'end': end,
                'speed_factor': round(rng.uniform(args.rain_min, args.rain_max), 3)}
    if kind == 'road_closure':
        return {'event_id': event_id, 'kind': kind, 'begin': begin, 'end': end,
                'edge_id': rng.choice(sorted(edges))}
    lane_id = rng.choice(sorted(lanes))
    length = lanes[lane_id]['length']
    lower = max(5.0, args.position_min_ratio * length)
    upper = 0.9 * length
    position = rng.uniform(lower, upper)
    return {'event_id': event_id, 'kind': kind, 'begin': begin, 'end': end,
            'lane_id': lane_id, 'position': round(position, 1),
            'position_tolerance': args.position_tolerance}


def conflicts(a, b, lanes):
    """Within one episode keep events on distinct physical targets."""
    if a['kind'] == 'lane_blockage' and b['kind'] == 'lane_blockage':
        if a['lane_id'] == b['lane_id']:
            return True
        if lanes[a['lane_id']]['edge_id'] == lanes[b['lane_id']]['edge_id']:
            return True
    if a['kind'] == 'road_closure' and b['kind'] == 'road_closure':
        return a['edge_id'] == b['edge_id']
    if a['kind'] == 'lane_blockage' and b['kind'] == 'road_closure':
        return lanes[a['lane_id']]['edge_id'] == b['edge_id']
    if a['kind'] == 'road_closure' and b['kind'] == 'lane_blockage':
        return a['edge_id'] == lanes[b['lane_id']]['edge_id']
    return False


def build_plan(args):
    rng = random.Random(args.seed)
    _, lanes, edges = catalog(args.net)
    rows = []
    counts = {'normal': 0, 'single': 0, 'multi': 0}
    for episode in range(args.episodes):
        draw = rng.random()
        if draw < args.normal:
            rows.append({'episode': episode, 'label': 'normal', 'events': []})
            counts['normal'] += 1
            continue
        kinds = [rng.choice(KINDS)] if draw < args.normal + args.single else \
            rng.sample(KINDS, 2)
        events = []
        for index, kind in enumerate(kinds):
            for _ in range(64):
                candidate = sample_event(rng, kind, index, episode, args, lanes, edges)
                if all(not conflicts(candidate, existing, lanes) for existing in events):
                    events.append(candidate)
                    break
            else:
                raise RuntimeError(f'No conflict-free target for episode {episode}')
        label = ('single' if len(events) == 1 else 'multi') + ':' + \
            '+'.join(e['kind'] for e in events)
        counts['single' if len(events) == 1 else 'multi'] += 1
        rows.append({'episode': episode, 'label': label, 'events': events})
    eval_data = yaml.safe_load(Path(args.eval).read_text())
    plan = {'schema_version': PLAN_SCHEMA, 'plan_id': args.plan_id,
            'episodes': rows, 'eval': eval_data}
    return plan, counts


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--net', default=str(ROOT / DEFAULT_NET))
    parser.add_argument('--eval', default=str(ROOT / DEFAULT_EVAL))
    parser.add_argument('--episodes', type=int, default=200)
    parser.add_argument('--seed', type=int, required=True)
    parser.add_argument('--plan-id', default='hz4x4_random_v1')
    parser.add_argument('--horizon', type=int, default=3600)
    parser.add_argument('--recovery', type=int, default=600)
    parser.add_argument('--normal', type=float, default=0.3)
    parser.add_argument('--single', type=float, default=0.4)
    parser.add_argument('--begin-min', type=int, default=600)
    parser.add_argument('--begin-max', type=int, default=1800)
    parser.add_argument('--dur-min', type=int, default=180)
    parser.add_argument('--dur-max', type=int, default=600)
    parser.add_argument('--rain-min', type=float, default=0.7)
    parser.add_argument('--rain-max', type=float, default=0.9)
    parser.add_argument('--position-min-ratio', type=float, default=0.25)
    parser.add_argument('--position-tolerance', type=float, default=20.0)
    parser.add_argument('--out', required=True)
    args = parser.parse_args()
    if not (0.0 <= args.normal <= 1.0) or not (0.0 <= args.single <= 1.0) \
            or args.normal + args.single > 1.0:
        raise ValueError('normal/single must be in [0,1] and sum to <= 1; multi takes the rest')

    plan, counts = build_plan(args)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(yaml.safe_dump(plan, sort_keys=False, allow_unicode=True))

    # Round-trip validation: reload, and check every row against the runtime's
    # target validator so generation-time errors surface before any run.
    loaded = load_plan(out)
    runtime, _, _ = catalog(args.net)
    for index, schedule in enumerate(loaded.episodes):
        runtime.set_schedule(schedule)
    manifest = {
        'plan_id': loaded.plan_id, 'plan_sha256': loaded.plan_sha256,
        'episodes': len(loaded.episodes), 'counts': counts,
        'args': {k: getattr(args, k) for k in vars(args) if k != 'out'},
        'net_sha256': runtime.net_sha256, 'out': str(out),
    }
    manifest_path = out.with_suffix('.manifest.json')
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + '\n')
    print(json.dumps({'plan': str(out), 'manifest': str(manifest_path),
                      'plan_sha256': loaded.plan_sha256, 'counts': counts}, indent=2))


if __name__ == '__main__':
    main()
