from pathlib import Path
import pandas as pd, numpy as np
R=Path(__file__).resolve().parents[1]; O=R/'analysis/FIG2C_MATCHED_GROUP_BELLMAN_AUDIT'; O.mkdir(exist_ok=True)
P=R/'analysis/plan1_observation_conditioned_outcomes'; scope='HOA_USED_100'; aliases={'sumohz1x1_config2':'S1','sumohz1x1':'S2','sumohz1x1_config4':'S3','sumohz1x1_config3':'S4'}
s=pd.read_csv(P/'strict_outcome_differences.csv',low_memory=False); s=s[(s.data_scope==scope)&(s.time_control=='none')&(s.seed_a==s.seed_b)].copy(); t=pd.read_csv(P/'all_checkpoint_target_components.csv',low_memory=False); t=t[(t.data_scope==scope)&(t.seed_a==t.seed_b)].copy()
keys=['state_'+str(i) for i in range(8)]+['current_phase','action']; s['observation_key']=s[keys].astype(str).agg('|'.join,axis=1); s['matched_group_id']=s.scene_pair+'|'+s.observation_key
bads=s.observation_key.str.contains('nan'); parsed=s.loc[bads,'match_group'].str.split('|');
for i,k in enumerate(keys): s.loc[bads,k]=parsed.map(lambda q:q[i] if len(q)>i else np.nan)
s['observation_key']=s[keys].astype(str).agg('|'.join,axis=1); s['matched_group_id']=s.scene_pair+'|'+s.observation_key
b=s[['matched_group_id','scene_pair','scene_a','scene_b','seed_a','seed_b','match_group','observation_key']+keys+['reward_a','reward_b','reward_difference_b_minus_a']].drop_duplicates(); b=b.rename(columns={'scene_a':'scene_i','scene_b':'scene_j','seed_a':'seed_i','seed_b':'seed_j','reward_a':'reward_i','reward_b':'reward_j','reward_difference_b_minus_a':'delta_reward_signed'}); b['scene_alias_i']=b.scene_i.map(aliases); b['scene_alias_j']=b.scene_j.map(aliases); b['scene_pair_alias']=b.scene_alias_i+'-'+b.scene_alias_j; b['delta_reward_abs']=b.delta_reward_signed.abs(); b['exact_observation_match']=True;b['exact_action_match']=True;b['pairing_rule']='existing generator: per scene/seed/key means; transition identity unavailable'; b.to_csv(O/'02_matched_group_base.csv',index=False)
t['observation_key']=t[keys].astype(str).agg('|'.join,axis=1); t['matched_group_id']=t.scene_pair+'|'+t.observation_key; e=t.rename(columns={'evaluator_seed':'evaluator_training_seed','bootstrap_component_difference_b_minus_a':'delta_bootstrap_signed','total_target_difference_b_minus_a':'delta_target_signed','reward_difference_b_minus_a':'delta_reward_signed'}); e['evaluator_id']=e.evaluator_scene+'_seed'+e.evaluator_training_seed.astype(str); e['delta_bootstrap_abs']=e.delta_bootstrap_signed.abs(); e['delta_target_abs']=e.delta_target_signed.abs(); e['delta_reward_abs']=e.delta_reward_signed.abs(); e.to_csv(O/'03_matched_group_evaluator_bellman.csv',index=False)
z=e.groupby('matched_group_id').agg(evaluator_count=('evaluator_id','nunique'),delta_b_median=('delta_bootstrap_signed','median'),delta_b_q1=('delta_bootstrap_signed',lambda x:x.quantile(.25)),delta_b_q3=('delta_bootstrap_signed',lambda x:x.quantile(.75)),delta_b_mean=('delta_bootstrap_signed','mean'),delta_b_std=('delta_bootstrap_signed','std'),delta_b_min=('delta_bootstrap_signed','min'),delta_b_max=('delta_bootstrap_signed','max'),delta_y_median=('delta_target_signed','median'),delta_y_q1=('delta_target_signed',lambda x:x.quantile(.25)),delta_y_q3=('delta_target_signed',lambda x:x.quantile(.75)),delta_y_mean=('delta_target_signed','mean'),delta_y_std=('delta_target_signed','std'),delta_y_min=('delta_target_signed','min'),delta_y_max=('delta_target_signed','max')).reset_index(); z=z.merge(b[['matched_group_id','scene_pair_alias','delta_reward_signed','delta_reward_abs']],on='matched_group_id',how='left'); z.to_csv(O/'04_matched_group_evaluator_summary.csv',index=False)
def st(v):
 v=np.asarray(v,float); return dict(n=len(v),median=np.median(v),mean=np.mean(v),q1=np.quantile(v,.25),q3=np.quantile(v,.75),p05=np.quantile(v,.05),p95=np.quantile(v,.95),std=np.std(v,ddof=1),mad=np.median(abs(v-np.median(v))))
pd.DataFrame([{'quantity':n,**st(v)} for n,v in [('delta_r',z.delta_reward_signed),('delta_b',z.delta_b_median),('delta_y',z.delta_y_median),('abs_delta_r',z.delta_reward_abs),('abs_delta_b',abs(z.delta_b_median)),('abs_delta_y',abs(z.delta_y_median))]]).to_csv(O/'06_global_distribution_summary.csv',index=False)
z.groupby('scene_pair_alias').size().rename('matched_group_count').reset_index().to_csv(O/'05_scene_pair_summary.csv',index=False)
(O/'00_README.md').write_text('# FIG2C matched-group Bellman audit\n\nHOA_USED_100 is formal episodes 1-100, time_control=none. Exact key is 8 lane-count fields + current phase + action; DQN input is 16-D (8 counts + phase one-hot). Existing formal evaluator uses target-network max Q, gamma=0.95, no terminal mask and no Double-DQN split. S1=sumohz1x1_config2, S2=base/raw sumohz1x1, S3=sumohz1x1_config4, S4=sumohz1x1_config3. Existing source tables are key/seed means; transition identity, next-observation values and source episode/step are not recoverable from them and are left explicitly absent.\n',encoding='utf-8')
(O/'01_provenance_audit.csv').write_text('artifact,source\nmatching,analysis/plan1_observation_conditioned_outcomes/strict_outcome_differences.csv\nbellman,analysis/plan1_observation_conditioned_outcomes/all_checkpoint_target_components.csv\nlogic,tools/plan1_observation_conditioned_outcomes.py\n',encoding='utf-8')
(O/'07_pseudoreplication_audit.md').write_text(f'# Pseudoreplication audit\n\nUnique keys: {b.observation_key.nunique()}; key-level matched groups: {len(b)}; evaluator rows: {len(e)}; evaluators: {e.evaluator_id.nunique()}. Evaluator rows are not independent environment samples. Existing files aggregate transitions within scene/seed/key; raw transition-pair count, source episodes/runs and one-to-one transition pairing are unavailable.\n',encoding='utf-8')
(O/'08_validation_report.md').write_text(f'# Validation\n\nExact key/action fields retained. Evaluator completeness: {e.evaluator_id.nunique()} evaluator IDs. Bellman identity max error: {np.max(abs(e.delta_target_signed-(e.delta_reward_signed+e.delta_bootstrap_signed))):.6g}. Missing transition identity and next-state fields are known source limitation.\n',encoding='utf-8')
